### ISSUE TITLE
bagaimana cara mengkonversi jid string ke object JID

### ISSUE THREAD

**Issue by salismazaya** [krypton-byte/neonize#11]

**Comment by salismazaya** [comment]
`from langchain.agents.tools import tool
from neonize.proto.Neonize_pb2 import JID
from data import MEDIA_MESSAGES
from client import client

@tool
def create_sticker(id_: str, image_id: int):
    """
    jika user ingin membuat sticker
    """
    client.send_sticker(id_, client.download_any(MEDIA_MESSAGES[image_id]))
    return "beri tau user. bahwa berhasil membuat sticker"

tools = [create_sticker]

`

dimana jid adalah nomor whatsapp format 62xxxx

**Comment by krypton-byte** [comment]
from neonize.proto.Neonize_pb2 import JID
JID(User="628xxxx", RawAgent=0, Device=0, Integrator=0, Server="s.whatsapp.net", IsEmpty=False)
