### ISSUE TITLE
failed to find libmagic

### ISSUE THREAD

**Issue by Hendroarifin** [krypton-byte/neonize#21]
from neonize.client import NewClient
ImportError: failed to find libmagic.  Check your installation

**Comment by krypton-byte** [comment]
If you are using Termux, you can install it using pkg (package manager)
```bash
$ pkg install sox
```

**Comment by Hendroarifin** [comment]
I'm sorry I didn't provide complete information beforehand

I'm currently using windows and python 3.10

Thank you in advance

**Comment by krypton-byte** [comment]
Try installing the python-magic-bin library, it should work.
```bash
pip install python-magic-bin
```

**Comment by Hendroarifin** [comment]
still showing the same error, please guide
![2024-04-11_17h23_35](https://github.com/krypton-byte/neonize/assets/106127615/4c96b2b4-f6b6-49de-9492-a382bd40f7a2)

**Comment by Hendroarifin** [comment]
yes, I think so
![2024-04-11_17h38_37](https://github.com/krypton-byte/neonize/assets/106127615/9f1158ca-6dd2-45b7-93dc-4542994c0f87)

**Comment by krypton-byte** [comment]
pip install python-magic==0.4.15

**Comment by Hendroarifin** [comment]
I have installed python-magic==0.4.15 as suggested but it still gives the same error

**Comment by Hendroarifin** [comment]
there is a fix, thank you
