### ISSUE TITLE
Sending message to group

### ISSUE THREAD

**Issue by Hendroarifin** [krypton-byte/neonize#36]
How to sending messages to groups?

**Comment by aqasemi** [comment]
see [examples folder](https://github.com/krypton-byte/neonize/tree/master/examples).

**Comment by Hendroarifin** [comment]
Sorry, I've seen the example, but there's only a message replay. There's no way to send a message directly to a group. I've also tried sending a message to a group using the group ID, but the message wasn't sent. Please help me.

**Comment by Hendroarifin** [comment]
> Sorry, I've seen the example, but there's only a message replay. There's no way to send a message directly to a group. I've also tried sending a message to a group using the group ID, but the message wasn't sent. Please help me.

**Comment by Hendroarifin** [comment]
> see [examples folder](https://github.com/krypton-byte/neonize/tree/master/examples).

Sorry, I've seen the example, but there's only a message replay. There's no way to send a message directly to a group. I've also tried sending a message to a group using the group ID, but the message wasn't sent. Please help me

**Comment by aqasemi** [comment]
there is a `client.send_message(chat, text)` in the example file. `send_message` takes two arguments: `to` a `JID` object, and `message` which can be either a `str` or a `Message` object.

e.g., this should work:
```python
from neonize.proto.Neonize_pb2 import JID

group_id = "..."

group_jid = JID(
    User=group_id,
    Device=0,
    Integrator=0,
    IsEmpty=False,
    RawAgent=0,
    Server="g.us",
)
client.send_message(group_jid, "hi there!")
```

**Comment by Hendroarifin** [comment]
> there is a `client.send_message(chat, text)` in the example file. `send_message` takes two arguments: `to` a `JID` object, and `message` which can be either a `str` or a `Message` object.
> 
> e.g., this should work:
> 
> ```python
> from neonize.proto.Neonize_pb2 import JID
> 
> @client.event(events.MessageEv)
> def on_message(client: NewClient, messageEv: events.MessageEv):
>     # echo messages!
>     text = message.Message.conversation or message.Message.extendedTextMessage.text
>     chat = message.Info.MessageSource.Chat
>     
>     client.send_message(chat, text)
> ```
> 
> or from a stored group id
> 
> ```python
> group_id = "..."
> group_jid = JID(
>     User=group_id,
>     Device=0,
>     Integrator=0,
>     IsEmpty=False,
>     RawAgent=0,
>     Server="g.us",
> )
> client.send_message(group_jid, "hi there!")
> ```

for the first code isn't it to reply to incoming messages?

while for the second code I have tried but it does not work, an error appears
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6e9ac826]

goroutine 17 [running, locked to thread]:
go.mau.fi/whatsmeow.(*Client).getOwnID(...)
/home/runner/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240619210240-329c2336a6f1/client.go:374
go.mau.fi/whatsmeow.(*Client).SendMessage(0x6f1ffe80?, {0x6ed7ed60?, 0x6f1fe660?}, {{0xc000318000, 0x12}, 0x0, 0x0, 0x0, {0xc00008864c, 0x4}}, ...)
/home/runner/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240619210240-329c2336a6f1/send.go:179 +0x126
main.SendMessage(0x7?, 0x1cf65294370, 0x22, 0x1cf6528fd10, 0x1f)
/home/runner/work/neonize/neonize/goneonize/main.go:119 +0x286

I've also tried with how to
client.send_message(build_jid('jid group'+@g.us,'text') but the message is also not sent (no error appears)

**Comment by aqasemi** [comment]
> for the first code isn't it to reply to incoming messages?

yes. but you can nonetheless send to groups other than those triggered the inbound message. 

This error is showing because you didn't run `client.connect()`
`client.connect()` will block the main thread. You can run it in a separate thread. Or run your logic in a new thread separately. 


>client.send_message(build_jid('jid group'[+@g.us](mailto:+@g.us),'text')

no error appears because the JID is wrong. it will output something like: `group_id@g.us@s.whatsapp.net` 
i've issued a PR to fix this. but in the main time you can do something like this:
```python
def build_jid(chat_id, server="s.whatsapp.net")
  return JID(
      User=chat_id,
      Device=0,
      Integrator=0,
      IsEmpty=False,
      RawAgent=0,
      Server=server,
  )
```

**Comment by Hendroarifin** [comment]
> > there is a `client.send_message(chat, text)` in the example file. `send_message` takes two arguments: `to` a `JID` object, and `message` which can be either a `str` or a `Message` object.
> > e.g., this should work:
> > ```python
> > from neonize.proto.Neonize_pb2 import JID
> > 
> > @client.event(events.MessageEv)
> > def on_message(client: NewClient, messageEv: events.MessageEv):
> >     # echo messages!
> >     text = message.Message.conversation or message.Message.extendedTextMessage.text
> >     chat = message.Info.MessageSource.Chat
> >     
> >     client.send_message(chat, text)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or from a stored group id
> > ```python
> > group_id = "..."
> > group_jid = JID(
> >     User=group_id,
> >     Device=0,
> >     Integrator=0,
> >     IsEmpty=False,
> >     RawAgent=0,
> >     Server="g.us",
> > )
> > client.send_message(group_jid, "hi there!")
> > ```
> 
> for the first code isn't it to reply to incoming messages?
> 
> while for the second code I have tried but it does not work, an error appears panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0x6e9ac826]
> 
> goroutine 17 [running, locked to thread]: go.mau.fi/whatsmeow.(*Client).getOwnID(...) /home/runner/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240619210240-329c2336a6f1/client.go:374 go.mau.fi/whatsmeow.(*Client).SendMessage(0x6f1ffe80?, {0x6ed7ed60?, 0x6f1fe660?}, {{0xc000318000, 0x12}, 0x0, 0x0, 0x0, {0xc00008864c, 0x4}}, ...) /home/runner/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240619210240-329c2336a6f1/send.go:179 +0x126 main.SendMessage(0x7?, 0x1cf65294370, 0x22, 0x1cf6528fd10, 0x1f) /home/runner/work/neonize/neonize/goneonize/main.go:119 +0x286
> 
> I've also tried with how to client.send_message(build_jid('jid group'[+@g.us](mailto:+@g.us),'text') but the message is also not sent (no error appears)

It seems I was not careful with this instruction, but now my problem has been solved with this. Thank you very much😊🙏
